site_name: Nabu Documentation
theme:
  name: material
  logo: assets/images/image.avif
  #  name: gitbook
  features:
    - navigation.sections
    - navigation.expand
    # - navigation.tabs
    # - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
#      primary: teal
#      primary: deep orange
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css
nav:
  - 🧭 Start here:
      - Introduction: index.md
      - Vision: vision.md
      - Why now?: why-now.md
  - 🧠 The Challenge:
      - The challenge: challenge.md
  - ✅ The Solution:
      - The Solution: solution.md
      - Strategy flywheel: flywheel.md
      - Ecosystem & economics: ecosystems.md
  - 🛠️ Nabu technology:
      - Roadmap: roadmap.md
      - Nabu technology: technology.md
  - 🏃‍♂️ GETTING STARTED:
      - "How to use nabu: a step by step guide": getting-started/how-to-use-nabu-a-step-by-step-guide.md
  - 💡 Knowledge Base:
      - Glossary: glossary.md

plugins:
  - search
  - tags
#  - section-index
#  - material-plausible
#  - git-revision-date-localized
extra_javascript:
  - assets/javascripts/extra.js
